# Generated by Django 4.2.3 on 2023-07-21 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("list", "0002_task"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["done", "-datetime"]},
        ),
    ]
