# Generated by Django 4.2.3 on 2023-07-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["done", "-created_at"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="datetime",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="task",
            name="tag",
            field=models.ManyToManyField(related_name="tasks", to="tasks.tag"),
        ),
    ]
