# Generated by Django 4.2.3 on 2023-07-21 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_task_options_rename_datetime_task_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "-created_at"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="done",
            new_name="is_done",
        ),
    ]
